##
## Copyright (c) 2023 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
##
## NVIDIA CORPORATION, its affiliates and licensors retain all intellectual
## property and proprietary rights in and to this material, related
## documentation and any modifications thereto. Any use, reproduction,
## disclosure or distribution of this material and related documentation
## without an express license agreement from NVIDIA CORPORATION or
## its affiliates is strictly prohibited.
##

model:
  horizon: 30
  state_filter_cfg:
    filter_coeff:
      position: 0.1
      velocity: 0.1
      acceleration: 0.0
    enable: True
  dt_traj_params:
    base_dt: 0.01
    base_ratio: 0.5
    max_dt: 0.04
  vel_scale: 1.0
  control_space: 'ACCELERATION'
  teleport_mode: False
  state_finite_difference_mode: "CENTRAL"


cost:
  pose_cfg:
    vec_weight: [1.0,1.0, 1.0, 1.0, 1.0, 1.0]
    run_vec_weight: [1.0,1.0, 1.0, 1.0, 1.0, 1.0]
    weight: [60,300.0,20,20] #[150.0, 2000.0, 30, 40]
    vec_convergence: [0.0, 0.00] # orientation, position
    terminal: True
    run_weight: 1.0
    use_metric: True

  cspace_cfg:
    weight: 1000.0
    terminal: True
    run_weight: 1.0

  bound_cfg:
    weight: [5000.0, 5000.0,5000.0,000.0]
    activation_distance: [0.1,0.1,0.1,0.1] # for position, velocity, acceleration and jerk
    smooth_weight: [0.0, 50.0, 0.0,0.0] # [vel, acc, jerk, alpha_vel, eta_position, eta_vel, eta_acc]
    run_weight_velocity: 0.0
    run_weight_acceleration: 1.0
    run_weight_jerk: 1.0
    null_space_weight: [10.0]

  primitive_collision_cfg:
    weight: 100000.0
    use_sweep: True
    sweep_steps: 4
    classify: False
    use_sweep_kernel: True
    use_speed_metric: False
    speed_dt: 0.1 # used only for speed metric
    activation_distance: 0.025

  self_collision_cfg:
    weight: 50000.0
    classify: False

  # NEW added: 접촉 임피던스 비용 파라미터를 구성해 MPC가 힘 추적을 학습. (한국어 주석)
  admittance_cfg:  # NEW added: 임피던스 비용에 사용될 파라미터 묶음. (한국어 주석)
    weight: [1.0, 1.0, 1.0, 0.1, 0.1, 0.1]  # NEW added: 힘/토크 축별 비용 가중치. (한국어 주석)
    desired_wrench: [0.0, 0.0, 5.0, 0.0, 0.0, 0.0]  # NEW added: 목표 접촉 렌치 설정. (한국어 주석)
    stiffness: [15.0, 15.0, 15.0, 0.0, 0.0, 0.0]  # NEW added: 위치 오차에 곱할 강성 계수. (한국어 주석)
    damping: [5.0, 5.0, 5.0, 0.0, 0.0, 0.0]  # NEW added: 속도 오차에 곱할 감쇠 계수. (한국어 주석)
    activation_threshold: 1.0  # NEW added: 활성화에 필요한 최소 힘 크기. (한국어 주석)


  stop_cfg:
    weight: 100.0 #50.0
    max_nlimit: 0.25 #0.2



mppi:
  init_cov          : 0.05 #.5 #.5
  gamma             : 0.98
  n_iters           : 5
  cold_start_n_iters: 5
  step_size_mean    : 0.9
  step_size_cov     : 0.01
  beta              : 0.1
  alpha             : 1
  num_particles     : 400 #10000
  update_cov        : True
  cov_type          : "DIAG_A" #
  kappa             : 0.0001
  null_act_frac     : 0.05
  sample_mode       : 'BEST'
  base_action       : 'REPEAT'
  squash_fn         : 'CLAMP'
  n_problems        : 1
  use_cuda_graph    : True
  seed              : 0
  store_debug       : False
  random_mean       : True
  sample_per_problem: False
  sync_cuda_time    : True
  use_coo_sparse    : True
  sample_params:
    fixed_samples: True
    sample_ratio: {'halton':0.3, 'halton-knot':0.7, 'random':0.0, 'random-knot':0.0}
    seed: 0
    filter_coeffs: [0.3, 0.3, 0.4]
    n_knots: 5
  debug_info:
    visual_traj       : 'ee_pos_seq'
  hierarchy_cfg:  # NEW added: 계층형 MPPI 우선순위와 가중치를 정의. (한국어 주석)
    task_order: ["safety", "admittance", "tracking"]  # NEW added: 우선순위 순서를 지정. (한국어 주석)
    task_weights:  # NEW added: 작업별 가중치 사전. (한국어 주석)
      safety: 1.0  # NEW added: 안전 비용에 적용할 가중치. (한국어 주석)
      admittance: 0.5  # NEW added: 임피던스 비용 가중치. (한국어 주석)
      tracking: 1.0  # NEW added: 추종 비용 가중치. (한국어 주석)
    feasibility_thresholds:  # NEW added: 허용 가능한 비용 한계. (한국어 주석)
      safety: 1.0e3  # NEW added: 안전 비용 허용 상한. (한국어 주석)
      admittance: 5.0e2  # NEW added: 임피던스 비용 허용 상한. (한국어 주석)
    violation_penalty: 1.0e4  # NEW added: 계층 위반 시 부과할 벌점. (한국어 주석)
    nullspace_damping: 0.2  # NEW added: 접촉 시 null-space 감쇠 계수. (한국어 주석)
    contact_activation_norm: 5.0  # NEW added: null-space 감쇠를 켜는 힘 노름 기준. (한국어 주석)
